# Generated by Django 3.1.5 on 2021-03-17 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BlogPart', '0002_blog_post_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upvote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(blank=True, editable=False, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Upvote',
                'verbose_name_plural': 'Upvotes',
            },
        ),
        migrations.CreateModel(
            name='Downvote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(blank=True, editable=False, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Downvote',
                'verbose_name_plural': 'Downvotes',
            },
        ),
        migrations.CreateModel(
            name='Blog_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downvote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_downvote', to='BlogPart.downvote')),
                ('posts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_posts', to='BlogPart.blog_post')),
                ('upvote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_upvote', to='BlogPart.upvote')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='blog_post',
            name='downvote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BlogPart.downvote'),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='upvote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BlogPart.upvote'),
        ),
    ]
