# Generated by Django 3.1.5 on 2021-03-17 16:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPart', '0003_auto_20210317_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_user',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
