# Generated by Django 3.1.5 on 2021-03-17 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPart', '0004_blog_user_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_user',
            name='downvote',
        ),
        migrations.RemoveField(
            model_name='blog_user',
            name='upvote',
        ),
    ]
