# Generated by Django 3.1.5 on 2021-03-17 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPart', '0005_auto_20210317_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_user',
            name='posts',
        ),
    ]
