# Generated by Django 3.1.5 on 2021-03-18 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPart', '0007_auto_20210318_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_user',
            old_name='username',
            new_name='user_name',
        ),
    ]
