# Generated by Django 3.1.5 on 2021-03-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPart', '0008_auto_20210318_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_post',
            name='downvote',
        ),
        migrations.RemoveField(
            model_name='blog_post',
            name='upvote',
        ),
        migrations.AddField(
            model_name='blog_post',
            name='feature_image',
            field=models.FileField(null=True, upload_to='media/post'),
        ),
    ]
